name: Automated Merge and Build

on:
  push:
    branches:
      - main

jobs:
  build-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        echo "Install dependencies here"

    - name: Run build
      run: |
        npm run build
        echo "Run build commands here"
    
    - name: Copy to temp-directory
      run: |
        ls /home
        # mkdir ~/temp-directory
        # cp -r app/* ~/temp-directory/
        # git checkout gt-build
        # cp -r ~/temp-directory/* .
        # git add .
        # git commit -m "Copy main-folder to gt-build branch"
    
    - name: Push to gt-build
      run: |
        git push origin gt-build
        
