name: Automated Merge and Build

on:
  push:
    branches:
      - main

jobs:
  build-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure Git
      run: |
        git config --global user.email "praliptarajoo@github.com"
        git config --global user.name "praliptarajoo"

    - name: Install dependencies
      run: |
        npm install
        echo "Install dependencies here"

    - name: Run build
      run: |
        npm run build
        echo "Run build commands here"
    
    - name: Fetch branches and create gt-build branch
      run: |
        git fetch origin
        
        # Create and checkout gt-build branch locally based on the remote branch
        # git checkout -B gt-build origin/gt-build
    
    - name: Copy to temp-directory
      run: |
        mkdir /tmp/temp-directory
        ls build/
        # cp -r app/* /tmp/temp-directory/
        # git checkout gt-build
        # cp -r /tmp/temp-directory/ .
        # git add .
        # git commit -m "Copy main-folder to gt-build branch"
        # ls
        echo 'Done'
    
    - name: Push to gt-build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin gt-build
        
